{% set version = "0.1.5" %}

package:
  name: allennlp-optuna
  version: {{ version }}

source:
  url: https://github.com/himkt/allennlp-optuna/archive/v{{ version }}.tar.gz
  sha256: d03c5b94e8806411a5e62a1074aaf6dfd4fe23c05a72837706bc3230e5459709

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6.1
    - pip
    - poetry
  run:
    - python >=3.6.1
    - allennlp >=1.1
    - optuna >=2.2,<3

test:
  imports:
    - allennlp_optuna

about:
  home: https://github.com/himkt/allennlp-optuna
  license: MIT
  license_file: LICENSE
  summary: AllenNLP plugin for adding subcommands to use Optuna, making hyperparameter optimization easy

  doc_url: https://allennlp-optuna.readthedocs.io/en/latest/
  dev_url: https://github.com/himkt/allennlp-optuna

extra:
  recipe-maintainers:
    - himkt
    - h-vetinari
